version: "3.9"
services:
  openpose:
    build: .
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /dev/snd:/dev/snd
      - ${DOCKER_VOLUME_PROCESSED_PATH}:/data/processed
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
