version: "3.9"
services:
  openpose:
    build: .
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /dev/snd:/dev/snd
      - /home/nia_data/raw:/data/raw 
      - /home/nia_data/processed:/data/processed
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
